### PR TITLE
Web UI language changes

### PR DESCRIPTION
**Pull request by gingerbeardman**
Changes:
- presset -> preset, in both .tpl and .ts
- remove "enable" on some options, it's implied by toggle switch
- WIFI -> Wi-Fi
- capitalisations, on one option label

Questions:
- what is "strongness"? needs a better word.
- what is Wi-Fi > Station?

### CODE REVIEW

**Comment by ramapcsx2** [comment]
It used to be "strength", as in scanline effect strength :)
Wi-Fi > Station is describing the 2 modes the radio can be configured to, either as a station (connected to home network router), or as an AP, where it provides a network to connect to.

Thanks for going over it :)

**Comment by ramapcsx2** [comment]
Is that 480i/576i button a graphic? It needs to be 480p/576p, since it's not outputting interlaced :p

**Comment by gingerbeardman** [comment]
That is styled text, so just changed it in commit above.

**Comment by gingerbeardman** [comment]
I checked RetroArch Shaders and they use the phrase "scanline intensity" so I've changed "strongness" to "intensity"

**Comment by gingerbeardman** [comment]
Also, this is really well made! Props @xperiments

**Comment by xperiments** [comment]
I will try to test it tomorrow, but looks great!! Top @gingerbeardman !!!

**Comment by xperiments** [comment]
Checked. GoGoGo

Good clean work @gingerbeardman (Sorry 4 my english errors)

**Comment by ramapcsx2** [comment]
Thanks for the good work :)

**Pull request merged**
