### PR TITLE
Use arduino i2c wire functions and increase i2c frequency to 400kHz. …

### PR DESCRIPTION
**Pull request by tedgreen99**
… Uses pins A4 (SDA) and A5 (SCL).

### CODE REVIEW

**Comment by tedgreen99** [comment]
Hi Rama,  I posted a message on the shumps forum explaining the rational for this change but it needs to approved by an admin before it will show up.

**Comment by ramapcsx2** [comment]
Hi, thanks for helping out! 

It took about a day for the admins at shumps to grant me access.

This looks like you're bypassing the bitbanger. 
I assumed the GBS used some form of odd timing or signaling, hence requiring it. I never tested the regular wiring library.

If this works, that'd be great! A standard library will be easier to port, for one, and it might even be faster with that 400khz setting. I don't know how fast the bitbanger works but it had some reserves when I tried reducing the delays. I could nearly remove them even.

I'll check this out! :)

**Comment by ramapcsx2** [comment]
Yep, this works out of the box. And it's super fast, too :)

I did a quick safety check and there's one problem so far:
Apparently the default for the wiring library is to enable the pull-up resistors.
I hope this can be disabled, as it would break 5V Arduino on 3.3V GBS operation.
I'll check the docs :)

**Comment by tedgreen99** [comment]
From what I could get out of the docs it seemed to imply that the i2c pins would follow the i2c spec and require external pull ups.  The example circuits have external pull ups.  I'll see if I can discern what the library is actually doing.

**Comment by ramapcsx2** [comment]
`Wire.begin();
  digitalWrite(SCL, LOW);
  digitalWrite(SDA, LOW);
  Wire.setClock(400000);`
This works well here :)
The GBS has external 2k7 pull-up resistors, so the Arduino should never drive an I2C pin (or any pin) high.

**Comment by tedgreen99** [comment]
I would be worried about a momentary current spike between the time from Wire.begin to the disabling of the pullups.
https://github.com/ninjablocks/arduino/blob/master/Wire/utility/twi.c
On line 69 it enables the pullups.
The Wire.begin is simple enough that we could use our own custom routine which doesn't enable the pullups.

**Comment by tedgreen99** [comment]
Actually, after thinking about it, I don't think there would be much issue with the solution you suggested.  The current should be pretty minimal and only for a short period.

**Comment by ramapcsx2** [comment]
On my analog scope, I couldn't even see the 5V blip. But the trigger fired, so it was there.

I like your idea of substituting twi_init().
There should be a way to override a library function. I remember reading about it somewhere.
I would then still do the manual pull-up disable, just to future proof this for when people start porting :)

**Comment by tedgreen99** [comment]
It's only possible to override a C++ function if it is declared as virtual.  Unfortunately the twi_init is not virtual so it would be necessary to have our own custom wire.begin function and call it instead.

**Comment by ramapcsx2** [comment]
Bummer. 
For now, I'm fine with just disabling the pull-ups after Wire.begin().
The 5V burst can only last for a few Arduino MCU cycles and it's likely that it doesn't even reach the 5275 I2C pins.
Each cycle is 62ns and it does like 7 cycles on calculation there + the function return.
The 2 lines have 33 Ohm in series and those 2k7 Ohm resistors to 3.3V (and the inputs of that original control processor).
Yeah, the burst won't even reach the resistors.

**Comment by ramapcsx2** [comment]
So with no load connected, there is a 5V blip for 0.1ms, going to to 3.3V in 0.2ms.
With the wire connected, there's nothing anymore.
Safe! :)

**Pull request merged**
