### PR TITLE
Preliminary OSD support

### PR DESCRIPTION
**Pull request by bkoropoff**
This allows changing screen alignment and size through the built-in OSD.  I'm using the buttons on the GBS board itself to control it, but it would be easy enough to hook up an IR receiver or similar.

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Do tell when you want this merged. 

I don't have the setup to test this, but I heard others mention IR support at least.
Wiring up all 4 buttons seems like a hassle now, especially with the web ui available.
They will be easy to support with the plug and hack adapters though :)

**Comment by ramapcsx2** [comment]
Hah, I found a couple unused command handler keys and can test this now. 
Awkward, but it works :)

The menu works very well already. I can see how this is useful with the buttons hooked up.
I guess I'll spend some time looking for free I/O pins on ESP32 and ESP8266 now.

One thing I noticed:
The button handler runs very frequently. Every time it runs, it first debounces the buttons.
This won't take long, of course, but if the loop finishes quickly / instantly, it might add up.

If it does add up, then the button check could run from an interrupt handler.
In that case, it only ever gets to work once a button press has been detected.

**Comment by bkoropoff** [comment]
I disabled `HAVE_BUTTONS` by default since pins left floating will cause phantom inputs.  That means this can be safely merged.

**Comment by ramapcsx2** [comment]
Yep!

**Comment by gingerbeardman** [comment]
Hi @bkoropoff @ramapcsx2 how do I go about using this? Wire up the buttons? If so, how? Thanks!

**Comment by ramapcsx2** [comment]
Where do you need help? :)

Pretty rough overview:
The Arduino code sets up bitfields with all the option bits, then sends them on each websocket update.
The Javascript should parse the bitfields and light up any set buttons as required.

**Comment by ramapcsx2** [comment]
Sorry if you got an Email with an earlier reply. I thought this was about the new web ui :)

For the OSD stuff, yes, you need to wire each button to a free GPIO (input) on the ESP8266.
It will be hard to find 4 free pins..

**Comment by gingerbeardman** [comment]
Ah, OK. 

I'd like to contribute code and figured OSD with GBS hardware buttons would be a good pairing with WebUI. We'll see.

**Pull request merged**
