### PR TITLE
Add and use interface to combine register reads/writes

### PR DESCRIPTION
**Pull request by bkoropoff**
This allows multiple registers in the same segment to be updated with a single I2C read and write cycle.

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Holy.. I've got to learn that stuff before merging, lol. ><

**Comment by bkoropoff** [comment]
Added some comments to the code for clarity

**Comment by ramapcsx2** [comment]
```
typedef GBS::Tie<GBS::VDS_VSYNC_RST, GBS::VDS_VS_ST, GBS::VDS_VS_SP> Regs;
auto plusDelta = [=](uint16_t x) { return x + delta; };
Regs::modify(plusDelta, plusDelta, plusDelta);
```
I'm sorry but is this really necessary?
It's nice if this saves some I2C traffic but is it worth the obfuscation?
Once merged, will there be more of this?

If there's any kind of bug in those new templates, I certainly will never find it.

**Comment by bkoropoff** [comment]
I can change it to a read followed by a write.  That retains the main
advantage, which is that the video timings change as close to
simultaneously as possible.

**Comment by ramapcsx2** [comment]
That would be easier to work with, yeah.
I didn't realize that this was to tighten video timing changes.
That's probably a good thing to do.

**Comment by bkoropoff** [comment]
Changed

**Pull request merged**
