### PR TITLE
Redesigned OLED menu. Better UI, easier development.

### PR DESCRIPTION
**Pull request by PSHarold**
Redesigned OLED menu

Main features:
1. Easier development and cleaner codes. You can now dynamically create menu items, thus supporting **showing preset names** rather than 1234567. (I remember that someone requested this feature.)
2. Translations. Menu items that need to be translated use xbm images instead of C/C++ strings. Run generate_translations.py to update translations (documentation to be added). Menu items can have varying font sizes.
3. Long text will automatically scroll.
4. Better UI. A unified status bar for going back and pagination.
5. Two new menu items for checking WiFI info and clearing connection (reset to AP mode). 
6. Shows a screensaver after 3 minutes (adjustable) of inactivity.

(Disabled by default. Change USE_NEW_OLED_MENU to 1 to enable)

Demo:
https://user-images.githubusercontent.com/10881220/213614897-e6e9bf90-1b00-456c-8b72-f55449562513.mp4

main
presets
cn

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Hey, I don't have the time to properly test this.. Does anyone else have the hardware and can give it a go? Cheers :)

**Comment by ramapcsx2** [comment]
Hey, I would merge this work, but I still need someone to check and verify whether the changes are working right.
I don't have the hardware, nor time ><

**Comment by PSHarold** [comment]
> Hey, I would merge this work, but I still need someone to check and verify whether the changes are working right. I don't have the hardware, nor time ><

OK Thanks. It's disabled by default. Should be safe to merge.

**Comment by lichtmetzger** [comment]
I love the new menu, it's really awesome and functionality-wise, it works pretty well with only minor issues. I tested the WiFi info, preset names, resolution changes and factory reset on my Bitfunx GBS-C.

- Is it intended that turning left goes down and turning right goes up in the menu? I think it should be the other way around, but maybe that's just me or my shady Aliexpress unit.
- When doing a factory reset, it displays "actory Restoring", because the F doesn't fit on the screen.

I also had quite a few problems building it.

First, there are a lot of -fpermissive errors I had to mute with `#pragma GCC diagnostic warning "-fpermissive"` in gbs-control.ino. I'm just a lousy PHP dev so not sure what's going on here, but I guess these should be fixed before merging.

Also, this errors out:
https://github.com/ramapcsx2/gbs-control/blob/5c16a43fd1218b51508f723fb2b25cc346cb0e5a/gbs-control.ino#L4273

That function expects a parameter, setting it to false here seems to work.

Proof it works:
BURST20230720175332230_COVER

**Comment by ramapcsx2** [comment]
@nyanpasu64 Do you have time and would want to check this PR out?
You'll need an OLED module though :p

**Comment by nyanpasu64** [comment]
I don't have an OLED panel to test this code. And I think https://github.com/ramapcsx2/gbs-control/pull/438 interacts with the OLED menu:

> * On the other hand, there might be code (`activeFrameTimeLockInitialSteps`?, `printVideoTimings`, `runSyncWatcher`?, `settingsMenuOLED`) which are _fixed_ by not setting `rto->presetID = {9,PresetCustomized}`.

> * I'm not sure if this code interacts correctly with the OLED menu, or if the old code did so either. Specifically `if (oled_menuItem == 4 && oled_subsetFrame == 1)` sets `rto->presetID = GBS::GBS_PRESET_ID::read()` without actually loading a different preset. This would previously cause the web UI to stop highlighting "load preset" even when a custom preset was loaded, but will no longer do so.

Yeah you need to call `setOutModeHdBypass(false)` if I recall correctly. You'd only need to set it to true when loading a custom preset, which I think your OLED code isn't doing.

Can anyone confirm that rebasing this PR on master works properly? Or @PSHarold could rebase and re-push? I don't have an OLED display to test, but if the code still works I could review the changes.

**Comment by PSHarold** [comment]
> I don't have an OLED panel to test this code. And I think #438 interacts with the OLED menu:
> 
> > * On the other hand, there might be code (`activeFrameTimeLockInitialSteps`?, `printVideoTimings`, `runSyncWatcher`?, `settingsMenuOLED`) which are _fixed_ by not setting `rto->presetID = {9,PresetCustomized}`.
> 
> > * I'm not sure if this code interacts correctly with the OLED menu, or if the old code did so either. Specifically `if (oled_menuItem == 4 && oled_subsetFrame == 1)` sets `rto->presetID = GBS::GBS_PRESET_ID::read()` without actually loading a different preset. This would previously cause the web UI to stop highlighting "load preset" even when a custom preset was loaded, but will no longer do so.
> 
> Yeah you need to call `setOutModeHdBypass(false)` if I recall correctly. You'd only need to set it to true when loading a custom preset, which I think your OLED code isn't doing.
> 
> Can anyone confirm that rebasing this PR on master works properly? Or @PSHarold could rebase and re-push? I don't have an OLED display to test, but if the code still works I could review the changes.

Rebased and re-pushed. But I currently don't have the dev environment to verify the rebased result. Could someone help verify that this is still working and does not overwrite the previous commtis?

**Comment by PSHarold** [comment]
> I love the new menu, it's really awesome and functionality-wise, it works pretty well with only minor issues. I tested the WiFi info, preset names, resolution changes and factory reset on my Bitfunx GBS-C.
> 
> * Is it intended that turning left goes down and turning right goes up in the menu? I think it should be the other way around, but maybe that's just me or my shady Aliexpress unit.
> * When doing a factory reset, it displays "actory Restoring", because the F doesn't fit on the screen.
> 
> I also had quite a few problems building it.
> 
> First, there are a lot of -fpermissive errors I had to mute with `#pragma GCC diagnostic warning "-fpermissive"` in gbs-control.ino. I'm just a lousy PHP dev so not sure what's going on here, but I guess these should be fixed before merging.
> 
> Also, this errors out:
> 
> https://github.com/ramapcsx2/gbs-control/blob/5c16a43fd1218b51508f723fb2b25cc346cb0e5a/gbs-control.ino#L4273
> 
> That function expects a parameter, setting it to false here seems to work.
> 
> Proof it works: BURST20230720175332230_COVER

Thanks! The control is indeed confusing even for me. I thought about making it configurable but didn't have the time.

**Comment by rickdgray** [comment]
This is a dope PR; any movement on it?

**Comment by nyanpasu64** [comment]
Sorry, Rama is too busy to work on the project and I don't have an OLED screen to test, so I don't know if it can be merged in the near future.

**Comment by rickdgray** [comment]
No worry. I'm starting my build here in a few days and I plan to put an OLED on mine. If it's any help, I can pull down and test it.

**Comment by ramapcsx2** [comment]
Guys, we can merge if someone at least watches for future complaints, lol. Would that work? :p

**Comment by nyanpasu64** [comment]
> Guys, we can merge if someone at least watches for future complaints, lol. Would that work? :p

I'm fine with that if I review the code before merging. Unfortunately the code is not usable in its current state. Looking through code:

- It's a big diff. It seems to be based on an existing repo at https://github.com/PSHarold/OLED-SSD1306-Menu?
- [ ] Why did you commit `.vscode/settings.json`? I sorta feel the project shouldn't include IDE-specific configuration (but I don't know this project well enough to set a hard rule).
- [ ] Is the new OLED menu even enabled? I see `#define USE_NEW_OLED_MENU 0` and the new code is hidden behind `#if USE_NEW_OLED_MENU`.
- [ ] If I enable the OLED menu, I get tons of warnings and many compilation errors (probably it used to compile before, but broke when merging in changes from master):
	- `uopt->presetPreference = preset` requires casting to `PresetPreference` now (or using enum literals rather than integer literals, if available).
	- `setOutModeHdBypass()` requires passing false unless you're in the middle of loading a custom preset (from a save slot). In your case you have to pass false.
	- I want to keep the project at zero warnings in the source code (outside of library dependencies).

<details>
<summary>Expand for build error log.</summary>

```
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuItem.cpp: In member function 'void OLEDMenuItem::calculate()':
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuItem.cpp:22:20: warning: enumeration value 'TEXT_ALIGN_CENTER_BOTH' not handled in switch [-Wswitch]
             switch (this->alignment) {
                    ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino: In function 'bool resolutionMenuHandler(OLEDMenuManager*, OLEDMenuItem*, OLEDMenuNav, bool)':
gbs-control:7311:32: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'PresetPreference' [-fpermissive]
         uopt->presetPreference = preset;
                                ^
gbs-control:7319:28: error: too few arguments to function 'void setOutModeHdBypass(bool)'
         setOutModeHdBypass();
                            ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:5133:6: note: declared here
 void setOutModeHdBypass(bool regsInitialized)
      ^
gbs-control:7320:32: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'PresetPreference' [-fpermissive]
         uopt->presetPreference = preset;
                                ^
In file included from /home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:37:0:
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino: At global scope:
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7262:19: warning: unused parameter 'nav' [-Wunused-parameter]
 OLED_MENU_HANDLER(resolutionMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino: In function 'bool presetSelectionMenuHandler(OLEDMenuManager*, OLEDMenuItem*, OLEDMenuNav, bool)':
gbs-control:7354:28: error: invalid conversion from 'int' to 'PresetPreference' [-fpermissive]
     uopt->presetPreference = 2;
                            ^
In file included from /home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:37:0:
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino: At global scope:
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7337:19: warning: unused parameter 'nav' [-Wunused-parameter]
 OLED_MENU_HANDLER(presetSelectionMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7368:19: warning: unused parameter 'nav' [-Wunused-parameter]
 OLED_MENU_HANDLER(presetsCreationMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7368:19: warning: unused parameter 'isFirstTime' [-Wunused-parameter]
 OLED_MENU_HANDLER(presetsCreationMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7395:19: warning: unused parameter 'nav' [-Wunused-parameter]
 OLED_MENU_HANDLER(resetMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7440:19: warning: unused parameter 'item' [-Wunused-parameter]
 OLED_MENU_HANDLER(currentSettingHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7512:19: warning: unused parameter 'nav' [-Wunused-parameter]
 OLED_MENU_HANDLER(wifiMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7512:19: warning: unused parameter 'isFirstTime' [-Wunused-parameter]
 OLED_MENU_HANDLER(wifiMenuHandler)
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/OLEDMenuManager.h:11:38: note: in definition of macro 'OLED_MENU_HANDLER'
 #define OLED_MENU_HANDLER(name) bool name(OLEDMenuManager *manager, OLEDMenuItem *item, OLEDMenuNav nav, bool isFirstTime)
                                      ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino: In function 'void initOLEDMenu()':
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:7563:19: warning: unused variable 'presetMenu' [-Wunused-variable]
     OLEDMenuItem *presetMenu = oledMenu.registerItem(root, MT_NULL, IMAGE_ITEM(OM_PRESET), presetsCreationMenuHandler);
                   ^
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino: In lambda function:
/home/nyanpasu64/code/gbs-c/gbs-control/gbs-control.ino:10216:9: warning: label 'fail' defined but not used [-Wunused-label]
         fail:
         ^
exit status 1
```

</details>

----

- Not sure where the contents of `resolutionMenuHandler` come from (juggling `rto->videoStandardInput != 15` etc.), but I don't understand the original code myself so I won't block the PR over this.
- In a version-controlled codebase, I generally prefer to change code to look like it was written that way, rather than commenting out old code (with the possible exception of changes intended to be reverted/reapplied in the future).

Screenshot_20240121_162021

- [ ] `typedef std::function<bool(OLEDMenuManager *, OLEDMenuItem *, OLEDMenuNav, bool)> MenuItemHandler;` may allocate behind the scenes, unlike a raw function pointer. This might be okay? Is it better to avoid dynamic allocations on an embedded platform?
	- This type is used by the two `OLEDMenuManager::registerItem` overloads (where `MenuItemHandler handler = nullptr`, I didn't even know std::function was nullable by default 😭).
	- I was able to replace the definition with `using MenuItemHandler = bool (*)(OLEDMenuManager *, OLEDMenuItem *, OLEDMenuNav, bool);`, and the project still builds, which indicates you probably only used bare functions rather than lambdas/objects which capture surrounding state (and require fat pointers like std::function).

I've pushed my build fix changes to this branch. You can drop, replace, or adapt my commits as you like. I did not fix the warnings you introduced, and expect them to be fixed before merging the PR. (@ramapcsx2 do you agree with this?)

- oops I let one warning slip through on an earlier PR (`warning: label 'fail' defined but not used`), I should fix it when I have time.

In my quick testing, the base GBS-C functionality (scaling and passthrough/bypass) appear to work like before, both with `#define USE_NEW_OLED_MENU 0` and `1`. I did not test the OLED functionality as I do not have an OLED screen.

**Comment by YoImLee** [comment]
I gave it a whirl and in terms of functionality it's certainly a step up from the current menu and far more responsive. There does seem to be a problem when loading custom presets. 

When I try selecting and loading a custom preset I have to press the rotary encoder's button a second time for it to actually work. It seems that when loading a custom preset for the first time it will load whatever preset was loaded before, then load the newly selected one when pressing the button a second time. The standard presets work as expected however.

It also seems like the max amount of custom presets that can be selected through the menu are 8, even when more are saved and available in the web UI.

https://github.com/ramapcsx2/gbs-control/assets/77938792/243e003d-5caa-417d-9ce3-1033e785bc22

**Comment by ramapcsx2** [comment]
Thanks a ton @nyanpasu64. What you describe is exactly the worry I had :)
@PSHarold or @rickdgray : Do you think you can address the remaining issues? I'm sorry that I can merely try to moderate here, but it would be neat to have this merged :)

**Comment by Metaln00b** [comment]
> Thanks a ton @nyanpasu64. What you describe is exactly the worry I had :)
> @PSHarold or @rickdgray : Do you think you can address the remaining issues? I'm sorry that I can merely try to moderate here, but it would be neat to have this merged :)

Touché😅

**Comment by PSHarold** [comment]
> Hey @ramapcsx2, I have my build mostly done; waiting on some shipments for remaining parts. I'm happy to give my best at debugging. C++ is not the language I use at work, but I know enough to be dangerous and think I can manage some help at least. Just be sure to correct any bad conventions or faux pas I might make. 😅
> 
> PS whoops commented on the wrong account

Working on it. Sorry for the delayed response, too busy these days.

**Pull request closed without merging**
